### ISSUE TITLE
Add Shortcode to display events

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#105]
Add a shortcode that can be used to display events. This would work something like:

[sc_events_list type='upcoming' number='5' category='meeting']

This would display a list of the 5 next upcoming events from the 'meeting' category.

ref: https://secure.helpscout.net/conversation/359060999/58543/?folderId=875342

**Comment by pippinsplugins** [comment]
We've had numerous requests for this so yes please!

**Comment by pippinsplugins** [comment]
@growdev need a couple of minor changes on the PR please.
