### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Sugar-Event-Calendar#16]

**Comment by pippinsplugins** [comment]
Unit tests connected with Travis! https://travis-ci.org/pippinsplugins/Sugar-Event-Calendar/branches

**Comment by pippinsplugins** [comment]
@growdev could you work on getting the tests finished now please?

**Comment by growdev** [comment]
@pippinsplugins most of the functions return a bunch of HTML with nonces inside of the output. 

1. Any suggestions for testing HTML returned including nonces?
2. Similar question: have you tested ajax functions that `die()` returning output including nonces?

**Comment by pippinsplugins** [comment]
1. Test that some of the HTML is there. Dont' worry about the nonces.

2. Ajax functions are _super_ hard to test. For now, let's skip them.

**Comment by growdev** [comment]
@pippinsplugins Cool thanks!

On this factory, is there too much code on the `event_non_recurring()` ?


https://github.com/pippinsplugins/Sugar-Event-Calendar/pull/56/commits/e56fbd21a69ce68abbf557aa6946900d1394b735

**Comment by pippinsplugins** [comment]
@growdev I'm not sure what you mean. I don't see `event_non_recurring()` in that commit. Could you clarify?

**Comment by growdev** [comment]
@pippinsplugins I mis-typed.  I meant `create_non_recurring()`.  Looking for some feedback on the factory.

**Comment by growdev** [comment]
.......................................                           39 / 39 (100%)

Time: 3.22 seconds, Memory: 42.25MB

OK (39 tests, 79 assertions)


Tests have been added and are passing. 

@pippinsplugins ready for review.

**Comment by pippinsplugins** [comment]
I'm seeing notices in the tests: https://travis-ci.org/pippinsplugins/Sugar-Event-Calendar/jobs/207516968

**Comment by growdev** [comment]
Notices are fixed. WP CLI was used over a year ago to scaffold test, and since then they updated their install script to pull down `tests/phpunit/data/` which includes a symlink that caused the notice since it didn't exist.

Current PHP7 tests are failing due to TravisCI update from last night.

**Comment by pippinsplugins** [comment]
@growdev could you see this fix that @drewapicture put into AffiliateWP to fix the PHP7 tests? https://github.com/AffiliateWP/AffiliateWP/commit/315e6cdf33cfea21b94838d120aeebe4379deab6

**Comment by growdev** [comment]
Applied and worked 👍    Thanks @drewapicture! 

![screen shot 2017-03-10 at 10 18 16 am](https://cloud.githubusercontent.com/assets/290886/23803068/effe6976-057a-11e7-8aa4-9a28e94ab5a4.png)

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
@growdev please see comments on PR.

**Comment by growdev** [comment]
@pippinsplugins gotcha. I will pull in what I need to finish the factory when #64 is merged.

**Comment by pippinsplugins** [comment]
@growdev could you address the undefined index in the tests? https://travis-ci.org/pippinsplugins/Sugar-Event-Calendar/jobs/211972267

Once that's done, we can merge and deploy!
