### ISSUE TITLE
Add new calendar views

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#20]
Along with month view add:
- [ ] Two Week view  (2week)
- [ ] Week view   (week)
- [ ] Four day view  (4day)
- [ ] Day view     (day)

These would be shortcodes.  Possibly add the ability to switch between views.

**Comment by pippinsplugins** [comment]
@growdev this is working great! Just one change we need: on the `4day` and `4day` types, we need to include the day of the month in the calendar headers, otherwise it's impossible to tell what day of the month it is.

**Comment by pippinsplugins** [comment]
Oh actually I guess the day number is still in the calendar cell . . . ok let's leave it as is. Merging!
