### ISSUE TITLE
Check how things look on mobile

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#21]

**Comment by pippinsplugins** [comment]
@growdev could we make some progress here?

**Comment by growdev** [comment]
Here's how the calendar will display in mobile (less than 480px wide) view.

![screen shot 2017-02-01 at 10 35 38 pm](https://cloud.githubusercontent.com/assets/290886/22537362/951e1c4e-e8cf-11e6-97d4-2c7691045284.png)

**Comment by pippinsplugins** [comment]
I like that display!

Will test today.

**Comment by pippinsplugins** [comment]
@growdev this is looking great!

While we're at it, let's go ahead and improve some of the spacing in the header:

<img width="371" alt="screen shot 2017-02-13 at 12 47 48 pm" src="https://cloud.githubusercontent.com/assets/1034109/22897801/b200f57e-f1ea-11e6-9c94-5343e9825f13.png">

**Comment by pippinsplugins** [comment]
I'd like to see the Go button on it's own line and the month header smaller with more space around it

**Comment by growdev** [comment]
Those controls are hidden on the mobile view. Did you have the latest code pulled when you took that screen shot?  

My view looks more like this:
![mobile](https://cloud.githubusercontent.com/assets/290886/23282892/e70c9ce0-f9e8-11e6-9bf1-ad70ed07c0ea.gif)

**Comment by pippinsplugins** [comment]
Working now! Must have been cache.

Merged!
