### ISSUE TITLE
Customize output of events in widget 

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#28]
Request:

![screenshot](https://cloud.githubusercontent.com/assets/290886/6813524/e71d167a-d243-11e4-8959-3017207864b0.png)

**Comment by pippinsplugins** [comment]
@growdev Could you please work on the upgrade routine and adjust the formatting (like I did in #48)?

**Comment by growdev** [comment]
I've opened #72 so I can clean up formatting globally when the release is ready to go.

I'm re-stating the tasks for this issue below so I can track if they are complete:

- [ ] Customized output of events in widget
	[] Title
	[] Date
	[] Time
	[] Categories
- [ ] Need an upgrade routine to ensure the behavior of widgets don't change 	
- [ ] Queries introduced are slow, 2-3 seconds of load time to the page
- [ ] The query needs to be fixed for when there are no upcoming or past events. It causes a fatal out of memory error.

**Comment by growdev** [comment]
This will probably need to be reworked after #62 is merged.

**Comment by growdev** [comment]
This is ready to test.  

Here are two widgets with the options to show/hide Widget title, Date, Time, and Categories. 
Upgrade routine exists. 

I'll need to refactor `sc_get_events_list()`  with the version in #62. Should I cherrypick what I need, or wait until that PR is merged?

![screen shot 2017-02-24 at 12 11 20 am](https://cloud.githubusercontent.com/assets/290886/23292523/0b42da9c-fa26-11e6-9899-37185f9c8b58.png)

**Comment by pippinsplugins** [comment]
Let's get #48 merged then continue here.

**Comment by growdev** [comment]
@pippinsplugins merge conflicts cleared and ready for review.

**Comment by pippinsplugins** [comment]
@growdev looks like the upgrade routine hasn't been completed yet.

Can you please finish that?

**Comment by growdev** [comment]
@pippinsplugins upgrade routine added.

**Comment by pippinsplugins** [comment]
Looks good!
