### ISSUE TITLE
Clean up code formatting globally

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#72]
Refer to @pippinsplugins  changes in #62 and fix formatting in all files.

- [x] Remove tabs from alignment (args list, series of variables)
- [x]  Fix indentation level of code blocks
- [x] Add all PHP Doc blocks
- [x] Properly wrap lines of HTML in PHP files

**Comment by growdev** [comment]
@pippinsplugins I'll finish this up when the other PR's are merged.

Question:  For doc blocks do you prefer

```
 * @since 1.0.0
 * @param array $args
 * @return array
```
or aligning over with spaces? 
```
 * @since         1.0.0
 * @param         array $args
 * @return        array
```

**Comment by pippinsplugins** [comment]
This is looking good. Let's merge this very last, however, so we can be sure we get everything all at once.

**Comment by pippinsplugins** [comment]
This is good for now.
