### ISSUE TITLE
Event titles cannot have custom HTML

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Sugar-Event-Calendar#88]
Titles are using `esc_html()` so it's not possible to wrap events in custom HTML through plugins that filter on `the_title`.

**Comment by pippinsplugins** [comment]
Previously addressed in https://github.com/pippinsplugins/Sugar-Event-Calendar/issues/67 but we didn't get them all.

**Comment by growdev** [comment]
@pippinsplugins was this found via a ticket, or looking through code?

**Comment by pippinsplugins** [comment]
Ticket.
