### ISSUE TITLE
Update recurring events display text

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#89]
On the single event page for recurring events change date display to be more clear of when recurring event starts:

Date: Starts October 5, 2017 then every Thursday until December 1, 2017

**Comment by growdev** [comment]
On the single event page for recurring events change date display to be more clear of when recurring event starts:

Date: Starts October 5, 2017 then every Thursday until December 1, 2017

**Comment by pippinsplugins** [comment]
Looks great!
