### ISSUE TITLE
Leap year calculation for yearly recurring events

### ISSUE THREAD

**Issue by growdev** [pippinsplugins/Sugar-Event-Calendar#92]
This recurring event will show up on June 13th in 2020.

![screen shot 2017-03-30 at 11 45 15 am](https://cloud.githubusercontent.com/assets/290886/24515969/c8d1660e-153e-11e7-9545-508cabf2b04a.png)

ref: https://secure.helpscout.net/conversation/341103036/56306/

**Comment by growdev** [comment]
Issue is here: https://github.com/pippinsplugins/Sugar-Event-Calendar/blob/master/includes/functions.php#L1061

The plugin saves meta for `sc_event_day_of_year` and `sc_event_end_day_of_year`  which is the numeric day of year. Leap years have 366 days not 365.  This will be off-by-one for Leap years.

**Comment by pippinsplugins** [comment]
Looks good, go ahead and merge and then submit a new PR with a version bump. I'll deploy after that.

**Comment by pippinsplugins** [comment]
Version 1.6.4 has been released.
