### ISSUE TITLE
timing issue when adding widgets in the Customizer

### ISSUE THREAD

**Issue by m-e-h** [pippinsplugins/Sugar-Event-Calendar#99]
When adding any SC widget from the Customizer, the initial values aren't registering.
I get `Notice: Undefined index: title in /var/www/html/wp-content/plugins/sugar-calendar/includes/widgets.php on line 31` until any of the options are edited or a title is added. If saved without editing, error is still present on the front-end.

Another example is shown in the attached image.
Even though initial calendar size setting is 'small', the preview shows 'large'. If left untouched 'large' is also the saved value.
![screenshot from 2017-04-21 13-48-02](https://cloud.githubusercontent.com/assets/3585901/25289832/40ca58da-2699-11e7-8d56-651c485b092b.png)

plugin version 1.6.4

**Comment by growdev** [comment]
@m-e-h thanks for the report. Found the issue and fixed in next version (1.6.5)
